FROM edward852/ubuntu-xfce-vnc-mapped-uid:latest
ARG OS=ubuntu
ARG DEBIAN_FRONTEND=noninteractive

#ADD ./comm/configs/ ${SHR_CONFIGS}/
#ADD ./${OS}/configs/ ${SHR_CONFIGS}/
ADD ./comm/scripts/ ${SHR_SCRIPTS}/
ADD ./${OS}/scripts/ ${SHR_SCRIPTS}/

RUN find ${SHR_SCRIPTS} -name '*.sh' -exec chmod a+x {} +
RUN ${SHR_SCRIPTS}/build/inst_dev_pkgs.sh
